name: Run Cypress e2e test against prod and staging

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'cypress/**'
jobs:
  cypress-run:
    name: Cypress run

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # checkout pull request HEAD commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Docker container
        run: DOCKER_TAG=e2e-test-runner ops/dockerfiles/e2e-test/build.sh
      - name: Run Cypress tests
        env:
          CYPRESS_TEST_APP_SECRET: ${{ secrets.TEST_APP_SIGNING_SECRET }}
        run: docker run --rm=true e2e-test-runner npm run run -- --app-secret "$CYPRESS_TEST_APP_SECRET"
